### ISSUE TITLE
Adding column when table is in sheet does not work

### ISSUE THREAD

**Issue by kmack3** [dataspread/dataspread-web#105]
<img width="1440" alt="screen shot 2017-09-14 at 1 09 33 pm" src="https://user-images.githubusercontent.com/12522796/30446184-ff219740-994d-11e7-98d4-02a72f9f2f25.png">

**Comment by Legandary23** [comment]
Should be fixed with the latest fix #37 `6ade96bd9caadc2a81d9ea347b91f9c9c4a34279`

**Comment by Legandary23** [comment]
Same issue as #37. Should be fixed in 6ade96bd9caadc2a81d9ea347b91f9c9c4a34279
