### ISSUE TITLE
[SYSTEM & FORMULA] - Formulae are not properly reloaded when closed & reopened

### ISSUE THREAD

**Issue by twattanawaroon** [dataspread/dataspread-web#112]
The reloaded value of a formula cell is the string
`org.zkoss.zss.model.impl.FormulaResultCellValu�
@8org.zkoss.zss.model.impl.CellImpl$InnerCellValu��org.zkoss.zss.model.impl.sys.formula.FormulaEngineImpl$FormulaExpressionImplSUM(A1:A3�[Lorg.zkoss.poi.ss.formula.ptg.Ptg�org.zkoss.poi.ss.formula.ptg.AreaPt�����org.zkoss.poi.ss.formula.ptg.AttrPt�`

**Comment by twattanawaroon** [comment]
See also screenshots from #96

**Comment by mangeshbendre** [comment]
Fixed in e0c18f0. A thorough check is required to make sure no other formulae are broken.
