### ISSUE TITLE
[FORMAT][SYSTEM] Spreadsheet stuck in "Processing" when formatting the entire spreadsheet

### ISSUE THREAD

**Issue by rahmansunny071** [dataspread/dataspread-web#121]
For example, here the user clicked on the entire range and changed the font to "Times New Roman"

![image](https://user-images.githubusercontent.com/8811607/30548476-dd6e28fe-9c57-11e7-881d-c22e1ce3e937.png)

**Comment by twattanawaroon** [comment]
Formatting unsupported in 0.5
