### ISSUE TITLE
Data upload error

### ISSUE THREAD

**Issue by dorisjlee** [dataspread/dataspread-web#128]
There should probably be some sort of example dataset that people can play with upfront or a interactive tutorial. I entered in Dataspread and was not too sure what to do.

I just tried uploading a sample csv file (the real estate dataset that we have from zenvisage) and it loaded for a while, then this message popped up.   Not really sure if I'm formatting my data correctly or there is some special header that I have to attach to the data file.

![screen shot 2017-09-19 at 11 29 47 pm](https://user-images.githubusercontent.com/5554675/30626918-de6e3be0-9d92-11e7-8e0f-c0dcc53e9264.png)

**Comment by mangeshbendre** [comment]
Please attach the CSV file here that caused the issue.

**Comment by dorisjlee** [comment]
https://github.com/zenvisage/zenvisage/blob/master/data/real_estate.csv

**Comment by mangeshbendre** [comment]
Configuration issue for Kite. Fixed.
