### ISSUE TITLE
[SYSTEM]Two different kinds of deleting

### ISSUE THREAD

**Issue by kmack3** [dataspread/dataspread-web#138]
If you actually select a cell and press the delete key, the cell seems to be reset. However, if you click on the cell, highlight the content, and press backspace, then the cell is NOT reset, it just has an empty string as the value. These two operations should take the cell to the same state: both reset

**Comment by twattanawaroon** [comment]
Wouldn't that be an expected behavior, particularly when the cell contains more than just a value, say, the cell has a background color assigned?
