### ISSUE TITLE
[FORMULA] dependency graph compressor works incorrectly

### ISSUE THREAD

**Issue by twattanawaroon** [dataspread/dataspread-web#139]
1. In A2 type `4`
1. In A3 type `=A2+2` (shows value 6)
1. In A1 type `0`
1. In A2 change to `=A1+2` (A2 shows value 2, A3 shows value 4)
1. In A1 change to `1`
expected behavior: A2 shows value 3, A3 shows value 5.
observed behavior: A2 shows value 3, A3 remains 4.

**Comment by mangeshbendre** [comment]
Fixed in 6a97036.
