### ISSUE TITLE
[SYSTEM][INTERFACE] Upload option doesn't work when navigating from Open

### ISSUE THREAD

**Issue by rahmansunny071** [dataspread/dataspread-web#140]
Open->Upload does not work but Import->Upload works. What is the purpose of having Open->Upload?

![image](https://user-images.githubusercontent.com/8811607/30989289-cc63bd0e-a462-11e7-827b-0246b4785896.png)

**Comment by Legandary23** [comment]
Open->Upload is importing a workbook while import->upload is only importing a sheet

**Comment by twattanawaroon** [comment]
Fixed in new interface.
