### ISSUE TITLE
Create table returned "the region is illegal"

### ISSUE THREAD

**Issue by kevinccchang** [dataspread/dataspread-web#25]
Selected region (A1, D12), Table > Create. Entered name "Members", and it showed error:

the region is illegal 1:A1[0,0,0,-1]

The region's content was:

First Name	Last_Name	Program	Email
Kelly	Mack	BS	knmack2@illinois.edu
Zekun	Fan	BS	zekun.fan@gmail.com
Albatool	Alamri	MS	aaalamr2@illinois.edu
Xinyan	Zhou	MS	xzhou14@illinois.edu
Mangesh	Bendre	PhD	bendre1@illinois.edu
Tana	Wattanawaroon	PhD	wattana2@illinois.edu
Yu	Lu	PhD	yulu3@illinois.edu
Sajjadur	Rahman	PhD	srahman7@illinois.edu
Karrie	Karahalios	Faculty	kkarahal@illinois.edu
Kevin	Chang	Faculty	kcchang@illinois.edu
Aditya	Parameswaran	Faculty	adityagp@illinois.edu

**Comment by mangeshbendre** [comment]
The create table will now respond back with the error received from the database.
