### ISSUE TITLE
[FORMULA] - Formula results show "..."

### ISSUE THREAD

**Issue by kevinccchang** [dataspread/dataspread-web#26]
Opened a worksheet with a formula in cells. The formula is like =CONCATENATE(A2," ",B2," <",D2,">"). The cells with formulas did not display the results, but showed only "...".

**Comment by mangeshbendre** [comment]
Since the computed values are not persisted, and triggering the computations during loading does not work while loading the formulae are shown as "...". This fix needs two things (a) persisting the dependency tree in db and (b) persist computed values in db.

**Comment by mangeshbendre** [comment]
The computed values are now stored in the database. The dependency tree is also persisted in the database.
