### ISSUE TITLE
Quick start table copy pasting has formatting issues and Querying the table fails

### ISSUE THREAD

**Issue by rahmansunny071** [dataspread/dataspread-web#33]
When copy-pasting "employlist" table from the quickstart guide, it adds extra space at the end of each cell in the first three column. When user creates a table, an underscore is added automatically to the column names.

When querying the table, it returns "#VALUE!"

![screenshot from 2017-09-05 16 51 54](https://user-images.githubusercontent.com/8811607/30086017-cade0112-925e-11e7-9e1c-aa50af63b883.png)

**Comment by mangeshbendre** [comment]
Added a trim to the column names. It will remove trailing spaces. Please re-check.

**Comment by rahmansunny071** [comment]
The column values also have a trailing space. I think that needs to be trimmed also. Otherwise, when running the query as shown in the tutorial, I get a [0X2] instead of [2X2] output.


![screenshot from 2017-09-06 09 46 53](https://user-images.githubusercontent.com/8811607/30118411-96db3b02-92e8-11e7-9d18-50c4dcf6cc70.png)
