### ISSUE TITLE
[SYSTEM] - Shift Cells "Right" has no effect

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#38]
![image](https://user-images.githubusercontent.com/1056605/30123548-0b810b94-92f8-11e7-9f4d-e0a93085e11e.png)

**Comment by Legandary23** [comment]
The actual problem is the interface is not refreshed intermediately.

**Comment by mangeshbendre** [comment]
For now, disable shift cells.

**Comment by Legandary23** [comment]
Disabled the option for now 758c83d2be78fe48c0c5227a9a135b27157be271
