### ISSUE TITLE
[FORMULA] - Extending the column to get similar formulae have no effect

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#39]
![image](https://user-images.githubusercontent.com/1056605/30123768-aa2d2ed0-92f8-11e7-97ba-be353a109f5f.png)

**Comment by mangeshbendre** [comment]
Fixed auto fill. Needs to be updated to work with INDEX functions. INDEX as numeric arguments that need to be updated.

**Comment by Legandary23** [comment]
Please implement the feature once we have the design.

**Comment by mangeshbendre** [comment]
Autofill now works. Opened issue for Index #84
