### ISSUE TITLE
[FORMAT] - Font says calibri but is actually Times New Roman

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#40]
![image](https://user-images.githubusercontent.com/1056605/30123830-da7c5840-92f8-11e7-9230-bd2f92ee4d4e.png)

**Comment by twattanawaroon** [comment]
Fonts that don't exist in the user's system will not be rendered correctly. However, the issue here exists even if the user has such fonts.
Perhaps we may want to switch to web fonts?

**Comment by rahmansunny071** [comment]
Can't seem to reproduce the issue. But there is another issue that falls into this category:
Even if user explicitly assigns Times New Roman to a range, it remains Calibri, unless you explicitly visit each cell and format them as TNR.

![image](https://user-images.githubusercontent.com/8811607/30493220-ed363a66-9a08-11e7-85e6-3b67ebc10b5c.png)

**Comment by twattanawaroon** [comment]
In fact, *range* formatting doesn't seem to work at all (font, size, bold, etc.).

**Comment by twattanawaroon** [comment]
Formatting unsupported in 0.5
