### ISSUE TITLE
Uninformative error with Table Name (What am I doing wrong?)

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#44]
![image](https://user-images.githubusercontent.com/1056605/30124998-a4281cd0-92fc-11e7-842b-affecf9c2bad.png)

**Comment by adityagp** [comment]
I see. Linking comes AFTER it is created. We should reorder the explanation in the Wiki. I thought Linking meant Creation

**Comment by mangeshbendre** [comment]
For now, we consider this as expected behavior for now. Paul, please update the document accordingly.

**Comment by adityagp** [comment]
Fine with me!

**Comment by Legandary23** [comment]
Updated the document for explaining the link function to eliminate the confusion.
