### ISSUE TITLE
[TABLE] - Table name weird capitalization issue

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#45]
I created a table name called "ages" -- I got the following message on create:
![image](https://user-images.githubusercontent.com/1056605/30125071-dcc314a0-92fc-11e7-8e83-2552f11b538f.png)

**Comment by mangeshbendre** [comment]
Fixed the change the table name to lower case. 
Assume that the underlying database does not store table names in a case sensitive manner. 
Fixed in commit 6d0be93 .
