### ISSUE TITLE
Insert row doesn't play nice with Tables

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#48]
Insert Row (not under the table subheading) throws an uninformative error

![image](https://user-images.githubusercontent.com/1056605/30125312-a5a77bea-92fd-11e7-9b9b-92d521906a0b.png)

We should either prevent this (error message -- "Insert Rows interferes with Table, use Table Option Instead") or something else.

Error message is: org.zkoss.zss.model.SCell.setValue(Ljava/lang/Object;Ljava/sql/Connection;Z)V

**Comment by Legandary23** [comment]
This should be fixed
