### ISSUE TITLE
Inserting empty rows leads to null pointer exception

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#50]
![image](https://user-images.githubusercontent.com/1056605/30125487-2214e802-92fe-11e7-9db7-cbd1919312ac.png)

**Comment by adityagp** [comment]
Server is hung after this
![image](https://user-images.githubusercontent.com/1056605/30125513-3814bdbc-92fe-11e7-9bbb-2f074d83125e.png)

**Comment by adityagp** [comment]
This crashed my computer!

**Comment by Legandary23** [comment]
Fix the issue with null pointer. Should not break the server and the computer.
