### ISSUE TITLE
[TABLE] - Can't seem to create table

### ISSUE THREAD

**Issue by adityagp** [dataspread/dataspread-web#56]
<img width="1115" alt="screen shot 2017-09-08 at 2 29 30 pm" src="https://user-images.githubusercontent.com/1056605/30228936-7c03b944-94a5-11e7-9b5d-c83491e5298c.png">

**Comment by mangeshbendre** [comment]
Invalid column name "1".  Will try to add a meaningful message.

**Comment by Legandary23** [comment]
Need to handle sql error

**Comment by mangeshbendre** [comment]
Added an error message if the column names are invalid.
Fixed in commit 6d0be93 .
