### ISSUE TITLE
[TABLE] - Add empty tuples under table

### ISSUE THREAD

**Issue by Legandary23** [dataspread/dataspread-web#61]
Add empty rows as tuples under a table will cause inconsistency between hybrid model and the actual table.

**Comment by Legandary23** [comment]
Besides, if I only add a value for one attribute, the entire row format of the table is not preserved. only the value cell I update will change the format. I think what we should have is whenever a row is added, the entire row of the table region should be changed to the table format.

**Comment by kmack3** [comment]
see comment, what should the default value of a cell be?

**Comment by Legandary23** [comment]
Good question, let's make is null for now, this should be discussed with the design of schema.

**Comment by kmack3** [comment]
constructor won't allow null. unless you mean the string "null"
