### ISSUE TITLE
A bunch of issues

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#62]
1. Null pointer exception when saving the book.
2. Can't save the size of the cells.
3. Null pointer exception when renaming sheet.
4. Sometimes I can't copy sheet. And the copy is always empty.
5. Deleting row can lead to fomula error.
6. Nothing in the export file.
7. Import file would always has sheet1 and sheet2 in addition.
8. Cut equals copy unless you reopen it.
9. When I click on cell I would see this sometimes:"Destination range must include source range and can be fill in one direction only".
10. Drag down the cell with fomular to a non empty cell would crash the server.
11. Tables I created when I was a guest can't be opened if I log in as a certain user.
12. When I created a table with formular, it shows  grammar mistake.
13. When I created a table, sometimes it showsthe region is illegal.
14. I can't modify the cell if it is part of a table or it is linked to a table.
15. When I used a index function using a table name like 'table1' as parameter instead of cell number like 'A1', I found '#ERROR!'.
16. If I created a table and copy the cells which I created the table, the copy will have the blue color as background though they actually don't link the any table. If I make a modify on the copy, next time I open it I would found on the copy that the part I modified is blue and others are white. Besides, I can't create a table based on the copy.
17. I can't create table on a combined table cell.

**Comment by twattanawaroon** [comment]
Can you separate each issue into its own issue entry? Steps to reproduce each error would be very helpful.
Also some are already tracked, for example 2. is #43 and 13. is #25

**Comment by nbajiaoshi** [comment]
Sure! I will do that soon.

Thanks,
Yu.
