### ISSUE TITLE
[SYSTEM] - Clear Content not working

### ISSUE THREAD

**Issue by Legandary23** [dataspread/dataspread-web#67]
Clear Content not working properly with the range.
It does delete the content, but the interface is not refreshed until the user manually reloads the sheet.

**Comment by rahmansunny071** [comment]
could you provide a screenshot? What us meant by Range here, when selecting a collection of cells?

**Comment by Legandary23** [comment]
When you select a range of cells and click on clear content, the contents are not deleted. However, if you close the book and reopen the book, you will find out that the contents of the range you selected are deleted.
