### ISSUE TITLE
Null pointer exception when renaming sheet.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#86]
When I rename the sheet on Chrome, windows 10, I see the null pointer exception. The name will remain unchanged. But if you refresh the Chrome and open the file again, the name will be updated.

**Comment by Legandary23** [comment]
Can you reproduce this issue and provide some screenshots?

**Comment by nbajiaoshi** [comment]
The circle part is a table.
![image](https://user-images.githubusercontent.com/15967722/30412301-2482a190-98dc-11e7-95af-d1524ed117db.png)
I try to modify the dept of Mike.
![image](https://user-images.githubusercontent.com/15967722/30412322-4cf9c77a-98dc-11e7-87e2-c59ddbfbe232.png)
It shows null pointer exception.
![image](https://user-images.githubusercontent.com/15967722/30412330-53f483f8-98dc-11e7-9f47-24e9d2eca28c.png)

**Comment by nbajiaoshi** [comment]
Now I have updated the code and found that this issue is gone.
