### ISSUE TITLE
[SYSTEM] - The copy of sheet is always empty

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#87]
The copy of sheet is always empty.
![image](https://user-images.githubusercontent.com/15967722/30361226-630d8f04-981b-11e7-9182-bbb1bbb03464.png)
![image](https://user-images.githubusercontent.com/15967722/30361256-97af5a76-981b-11e7-841e-d90429a5c9d6.png)

Sometimes I can't copy the sheet successfully.

**Comment by nbajiaoshi** [comment]
>

**Comment by twattanawaroon** [comment]
When the fix is merged to master, this issue will be closed.
