### ISSUE TITLE
Deleting row can crash the server.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#88]
Notice the formula in B11. Maybe this is because when the row is deleted, A11 are no longer a number.
![image](https://user-images.githubusercontent.com/15967722/30361296-c7982894-981b-11e7-9103-f568ad80c368.png)
![image](https://user-images.githubusercontent.com/15967722/30361307-d26bd4dc-981b-11e7-8741-277682ebdbd0.png)
We can see the server is crashed on the upper left corner.
![image](https://user-images.githubusercontent.com/15967722/30361411-721f94f0-981c-11e7-9419-cb87e1bac88e.png)

**Comment by mangeshbendre** [comment]
Add/delete row/column should not crash the server. 
The formulae are not yet updated for row/column inserts/delete, see #99.
