### ISSUE TITLE
Opening book cause "Not unique in ID space [Page mX9P_]: "

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#89]
Combo 1:
Import a book.
![image](https://user-images.githubusercontent.com/15967722/30361612-9d9e5fde-981d-11e7-9690-f8adb5fc76c2.png)

Error 1 
![image](https://user-images.githubusercontent.com/15967722/30361635-bce7cf2e-981d-11e7-8ca1-12a6180f5573.png)

If you open a new file after Error 1, you will see Error 2.
![image](https://user-images.githubusercontent.com/15967722/30361552-3d3cb366-981d-11e7-9af9-5afa86553030.png)
Error 2: "Not unique in ID space [Page mX9P_]: ".
![image](https://user-images.githubusercontent.com/15967722/30361555-430132c2-981d-11e7-8e0b-baacba312261.png)

**Comment by nbajiaoshi** [comment]
Combo 2:
Import another book.
![image](https://user-images.githubusercontent.com/15967722/30361612-9d9e5fde-981d-11e7-9690-f8adb5fc76c2.png)

Error 3 

![image](https://user-images.githubusercontent.com/15967722/30362031-825a5b40-981f-11e7-9257-07149e89c5de.png)


If you open a new file after Error 3, the server will be crashed.
![image](https://user-images.githubusercontent.com/15967722/30362056-a04faaba-981f-11e7-8eb9-03135d0d1dd9.png)

![image](https://user-images.githubusercontent.com/15967722/30362102-ef470ac8-981f-11e7-8cf3-42ec6e221850.png)

**Comment by mangeshbendre** [comment]
This is related to #69 
Fixed in commit 2e9b91a.
