### ISSUE TITLE
Import file would always has sheet1 and sheet2 in addition.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#90]
Import a book testbook .
![image](https://user-images.githubusercontent.com/15967722/30362414-7ccf1402-9821-11e7-94de-7b3e68959533.png)

![image](https://user-images.githubusercontent.com/15967722/30362338-2a273090-9821-11e7-8fd9-0933d40a34b3.png)
You will see two sheets in addition.
![image](https://user-images.githubusercontent.com/15967722/30362385-535938f0-9821-11e7-8e04-2dd66fa94e10.png)

**Comment by mangeshbendre** [comment]
Fixed in commit 2e9b91a.
