### ISSUE TITLE
Cut equals copy unless you reopen it.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#91]
![image](https://user-images.githubusercontent.com/15967722/30363087-7cc6312c-9824-11e7-9e82-2f17aeb735af.png)
![image](https://user-images.githubusercontent.com/15967722/30363093-81df7ff6-9824-11e7-84e7-e530f94338fa.png)

**Comment by Legandary23** [comment]
#67 This is the same issue as clear content.
