### ISSUE TITLE
Drag down the cell with fomular to a non empty cell would crash the server

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#93]
![image](https://user-images.githubusercontent.com/15967722/30363412-a39ad072-9825-11e7-9315-72689bf1bec5.png)

![image](https://user-images.githubusercontent.com/15967722/30363451-ca5154b6-9825-11e7-9b72-b07dfd7af4eb.png)

**Comment by mangeshbendre** [comment]
This should be fixed in  9da5bc5. Please retest and check.
