### ISSUE TITLE
When I create a table with formular, it shows  grammar mistake

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#95]
![image](https://user-images.githubusercontent.com/15967722/30363580-5edbc5a8-9826-11e7-9b7f-f7d9e0aeccce.png)
![image](https://user-images.githubusercontent.com/15967722/30363590-69726e5e-9826-11e7-8f7d-a5597262ebee.png)

**Comment by mangeshbendre** [comment]
Please post the error message in English.

**Comment by Legandary23** [comment]
#72 Seems like a duplicate issue.
