### ISSUE TITLE
[TABLE] - I can't modify the cell if it is part of a table or it is linked to a table

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#96]

**Comment by Legandary23** [comment]
Please provide details of this issue.

**Comment by nbajiaoshi** [comment]
The circle part is a table.
![image](https://user-images.githubusercontent.com/15967722/30412301-2482a190-98dc-11e7-95af-d1524ed117db.png)
I try to modify the dept of Mike.
![image](https://user-images.githubusercontent.com/15967722/30412322-4cf9c77a-98dc-11e7-87e2-c59ddbfbe232.png)
It shows null pointer exception.
![image](https://user-images.githubusercontent.com/15967722/30412330-53f483f8-98dc-11e7-9f47-24e9d2eca28c.png)

**Comment by Legandary23** [comment]
Can not reproduce the issue. Can you try it again and see if the issue is still there.

**Comment by twattanawaroon** [comment]
Neither can I.

**Comment by nbajiaoshi** [comment]
@Legandary23 @twattanawaroon 
Yes, the issue still there. I can produce the issue when I run the source code on my computer. But I can't produce it on our online site. I don't know why, the code is up-to-date.

**Comment by twattanawaroon** [comment]
I can only reproduce this locally; when redeploying the system, the sheet that were last opened would get into this problematic state.

**Comment by Legandary23** [comment]
can you guys clear the tables in the database and try that again? See if you can reproduce the issue.

**Comment by Legandary23** [comment]
@nbajiaoshi Can you clean the cache and check if this issue is still there?

**Comment by nbajiaoshi** [comment]
Now the issue is gone.
