### ISSUE TITLE
[TABLE & SYSTEM] - Error in copying cells within a table.

### ISSUE THREAD

**Issue by nbajiaoshi** [dataspread/dataspread-web#98]
The selected part is a table. 
![image](https://user-images.githubusercontent.com/15967722/30363779-196f9624-9827-11e7-9ba0-35a529220e68.png)

Copy it.

![image](https://user-images.githubusercontent.com/15967722/30363837-48e52bb2-9827-11e7-88c4-357a94dec361.png)

Change the Jesse to ddd in the copy.
![image](https://user-images.githubusercontent.com/15967722/30363856-62038f1c-9827-11e7-9097-c90c2e6faca0.png)

Close it and then open it.
![image](https://user-images.githubusercontent.com/15967722/30363866-6b963750-9827-11e7-8a15-006413c520f9.png)

What's wrong with the color?

**Comment by Legandary23** [comment]
The format of the pasted table should be changed back to normal cells. There is no link between the copied table and the database table.
